// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#ifndef _VITMITATRONICS_UI_H
#define _VITMITATRONICS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Home.h"
#include "ui_Recipe_Selection.h"
#include "ui_Customisation.h"
#include "ui_Cooking.h"
#include "ui_ChkIngredients.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png
LV_IMG_DECLARE(ui_img_chef_hat_png);    // assets/chef_hat.png
LV_IMG_DECLARE(ui_img_vit_mitatronics_png);    // assets/VIT_Mitatronics.png
LV_IMG_DECLARE(ui_img_387274184);    // assets/Recipe Image/masoor-dal.png
LV_IMG_DECLARE(ui_img_39411831);    // assets/Recipe Image/spinach-soup.png
LV_IMG_DECLARE(ui_img_162746961);    // assets/Recipe Image/tomato-soup.png
LV_IMG_DECLARE(ui_img_190461950);    // assets/Recipe Image/tur-dal.png
LV_IMG_DECLARE(ui_img_chevron_png);    // assets/chevron.png
LV_IMG_DECLARE(ui_img_spices_png);    // assets/spices.png
LV_IMG_DECLARE(ui_img_warning_png);    // assets/warning.png
LV_IMG_DECLARE(ui_img_drop_png);    // assets/drop.png
LV_IMG_DECLARE(ui_img_tomato_png);    // assets/tomato.png

// FONTS
LV_FONT_DECLARE(ui_font_Roboto_black_26);
LV_FONT_DECLARE(ui_font_Roboto_black_50);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
