// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#ifndef UI_CHKINGREDIENTS_H
#define UI_CHKINGREDIENTS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ChkIngredients
extern void ui_ChkIngredients_screen_init(void);
extern void ui_ChkIngredients_screen_destroy(void);
extern void ui_event_ChkIngredients(lv_event_t * e);
extern lv_obj_t * ui_ChkIngredients;
extern void ui_event_BackToHome(lv_event_t * e);
extern lv_obj_t * ui_BackToHome;
extern lv_obj_t * ui_Status;
extern lv_obj_t * ui_Cumin;
extern lv_obj_t * ui_CuminBar;
extern lv_obj_t * ui_SaltLabel;
extern lv_obj_t * ui_SaltBar;
extern lv_obj_t * ui_SaltIcon2;
extern lv_obj_t * ui_CuminIcon;
extern lv_obj_t * ui_CuminLabel;
extern lv_obj_t * ui_WarningSalt;
extern lv_obj_t * ui_WarningCumin;
extern lv_obj_t * ui_Salt;
extern lv_obj_t * ui_TurmericBar;
extern lv_obj_t * ui_TurmericIcon;
extern lv_obj_t * ui_TurmericLabel;
extern lv_obj_t * ui_MustardBar;
extern lv_obj_t * ui_MustardIcon;
extern lv_obj_t * ui_WarningMustard;
extern lv_obj_t * ui_MustardLabel;
extern lv_obj_t * ui_WarningTurmeric;
extern lv_obj_t * ui_Pepper;
extern lv_obj_t * ui_PepperBar;
extern lv_obj_t * ui_WarningPepper;
extern lv_obj_t * ui_PepperIcon;
extern lv_obj_t * ui_PepperLabel2;
extern lv_obj_t * ui_Water;
extern lv_obj_t * ui_WaterBar;
extern lv_obj_t * ui_WarningWater;
extern lv_obj_t * ui_WaterIcon;
extern lv_obj_t * ui_OilBar;
extern lv_obj_t * ui_WarningOil;
extern lv_obj_t * ui_OilIcon;
extern lv_obj_t * ui_WaterLabel;
extern lv_obj_t * ui_OilLabel;
extern lv_obj_t * ui_Tomato;
extern lv_obj_t * ui_TomatoBar;
extern lv_obj_t * ui_WarningTomato;
extern lv_obj_t * ui_TomatoIcon;
extern lv_obj_t * ui_TomatoLabel;
extern lv_obj_t * ui_SpinachBar;
extern lv_obj_t * ui_SpinachIcon;
extern lv_obj_t * ui_SpinachLabel;
extern lv_obj_t * ui_WarningSpinach;
extern lv_obj_t * ui_Onion;
extern lv_obj_t * ui_OnionBar;
extern lv_obj_t * ui_WarningOnion;
extern lv_obj_t * ui_OnionIcon;
extern lv_obj_t * ui_OnionLabel;
extern lv_obj_t * ui_GarlicBar;
extern lv_obj_t * ui_GarlicIcon;
extern lv_obj_t * ui_WarningGarlic;
extern lv_obj_t * ui_GarlicLabel;
extern lv_obj_t * ui_Image9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

