// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#ifndef UI_COOKING_H
#define UI_COOKING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Cooking
extern void ui_Cooking_screen_init(void);
extern void ui_Cooking_screen_destroy(void);
extern lv_obj_t * ui_Cooking;
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_UiCurrentProcessLabel;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

