// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#ifndef UI_CUSTOMISATION_H
#define UI_CUSTOMISATION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Customisation
extern void ui_Customisation_screen_init(void);
extern void ui_Customisation_screen_destroy(void);
extern lv_obj_t * ui_Customisation;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern void ui_event_Slider3(lv_event_t * e);
extern lv_obj_t * ui_Slider3;
extern void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label9;
extern void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label10;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

