// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#include "ui.h"

lv_obj_t * ui_Cooking = NULL;
lv_obj_t * ui_Arc2 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_UiCurrentProcessLabel = NULL;
lv_obj_t * ui_Image2 = NULL;
// event funtions

// build funtions

void ui_Cooking_screen_init(void)
{
    ui_Cooking = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Cooking, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Cooking, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc2 = lv_arc_create(ui_Cooking);
    lv_obj_set_width(ui_Arc2, 330);
    lv_obj_set_height(ui_Arc2, 328);
    lv_obj_set_x(ui_Arc2, -10);
    lv_obj_set_y(ui_Arc2, 1);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc2, 50);

    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0xE65062), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Cooking);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -48);
    lv_obj_set_y(ui_Label11, 36);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "FINISHES IN:");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Roboto_black_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Cooking);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 73);
    lv_obj_set_y(ui_Label12, 37);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "00:00 ");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFB52E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Roboto_black_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Cooking);
    lv_obj_set_width(ui_Panel4, 727);
    lv_obj_set_height(ui_Panel4, 50);
    lv_obj_set_x(ui_Panel4, -12);
    lv_obj_set_y(ui_Panel4, 174);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_UiCurrentProcessLabel = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_UiCurrentProcessLabel, 692);
    lv_obj_set_height(ui_UiCurrentProcessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_UiCurrentProcessLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_UiCurrentProcessLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_UiCurrentProcessLabel, "Current process... dynamically updated in code");
    lv_label_set_recolor(ui_UiCurrentProcessLabel, "true");
    lv_obj_set_style_text_align(ui_UiCurrentProcessLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UiCurrentProcessLabel, &ui_font_Roboto_black_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Cooking);
    lv_img_set_src(ui_Image2, &ui_img_chef_hat_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image2, -5);
    lv_obj_set_y(ui_Image2, -54);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Cooking_screen_destroy(void)
{
    if(ui_Cooking) lv_obj_del(ui_Cooking);

    // NULL screen variables
    ui_Cooking = NULL;
    ui_Arc2 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Panel4 = NULL;
    ui_UiCurrentProcessLabel = NULL;
    ui_Image2 = NULL;

}
