// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void SetMasoorDal(lv_event_t * e);
void SetSpinachSoup(lv_event_t * e);
void SetTomatoSoup(lv_event_t * e);
void SetTurDal(lv_event_t * e);
void UpdateSpiceLevel(lv_event_t * e);
void UpdateSalt(lv_event_t * e);
void StartCooking(lv_event_t * e);
void IngredientBarSetup(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
