// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#include "ui.h"

lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_ToStatusChk = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image11 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Recipe_Selection, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Recipe_Selection_screen_init);
    }
}

void ui_event_ToStatusChk(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ChkIngredients, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ChkIngredients_screen_init);
    }
}

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Home, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Home);
    lv_obj_set_width(ui_Button1, 259);
    lv_obj_set_height(ui_Button1, 52);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, 124);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFD1DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 35, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label2, 232);
    lv_obj_set_height(ui_Label2, 29);
    lv_obj_set_x(ui_Label2, 1);
    lv_obj_set_y(ui_Label2, 1);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Explore Recipe");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFB52E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Roboto_black_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToStatusChk = lv_btn_create(ui_Home);
    lv_obj_set_width(ui_ToStatusChk, 98);
    lv_obj_set_height(ui_ToStatusChk, 54);
    lv_obj_set_x(ui_ToStatusChk, 343);
    lv_obj_set_y(ui_ToStatusChk, 203);
    lv_obj_set_align(ui_ToStatusChk, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ToStatusChk, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ToStatusChk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ToStatusChk, lv_color_hex(0xFFD1DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ToStatusChk, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ToStatusChk, lv_color_hex(0xD88C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ToStatusChk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_ToStatusChk);
    lv_obj_set_width(ui_Label16, 86);
    lv_obj_set_height(ui_Label16, 55);
    lv_obj_set_x(ui_Label16, 3);
    lv_obj_set_y(ui_Label16, 1);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Status Check");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFB52E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label16, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_Roboto_black_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_Home);
    lv_img_set_src(ui_Image7, &ui_img_chef_hat_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image7, 3);
    lv_obj_set_y(ui_Image7, -136);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_img_create(ui_Home);
    lv_img_set_src(ui_Image11, &ui_img_vit_mitatronics_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 722
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 104
    lv_obj_set_x(ui_Image11, 3);
    lv_obj_set_y(ui_Image11, -12);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ToStatusChk, ui_event_ToStatusChk, LV_EVENT_ALL, NULL);

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    ui_Home = NULL;
    ui_Button1 = NULL;
    ui_Label2 = NULL;
    ui_ToStatusChk = NULL;
    ui_Label16 = NULL;
    ui_Image7 = NULL;
    ui_Image11 = NULL;

}
