// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#ifndef UI_RECIPE_SELECTION_H
#define UI_RECIPE_SELECTION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Recipe_Selection
extern void ui_Recipe_Selection_screen_init(void);
extern void ui_Recipe_Selection_screen_destroy(void);
extern lv_obj_t * ui_Recipe_Selection;
extern lv_obj_t * ui_Panel1;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label3;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label4;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Image10;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

